language: julia

os:
  - osx
  - linux

julia:
  - 1.2

notifications:
  email: false


after_success:
  - julia -e 'cd(Pkg.dir("ParamLevelSet")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
