language: julia

os:
  - linux

julia:
  - 1.2

notifications:
  email: false

script:
  - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test("ParamLevelSet";coverage=true);'

after_success:
  - julia -e 'using Pkg; import ParamLevelSet; cd(joinpath(dirname(pathof(ParamLevelSet)), "..", paths...)); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
