language: julia

os:
  - linux

julia:
  - 1.2

notifications:
  email: false

script:
  - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test(coverage=true);'

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("ParamLevelSet")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'